package com.synthverse.synthscape.core;

public enum Event {
    DETECTED_RAW_RESOURCE(0, EventType.DETECTION),
    DETECTED_PROCESSED_RESOURCE(1, EventType.DETECTION),
    DETECTED_EXTRACTED_RESOURCE(2, EventType.DETECTION),
    EXTRACTED_RESOURCE(3, EventType.EXTRACTION),
    PROCESSED_RESOURCE(4, EventType.PROCESSING),
    LOADED_RESOURCE(5, EventType.TRANSPORTATION),
    UNLOADED_RESOURCE(6, EventType.TRANSPORTATION),
    COLLECTED_RESOURCE(7, EventType.COLLECTION),
    
    SENT_RAW_RESOURCE_TRAIL(8, EventType.COMMUNICATION),
    RECEIVED_RAW_RESOURCE_TRAIL(9, EventType.COMMUNICATION),
    SENT_EXTRACTED_RESOURCE_TRAIL(10, EventType.COMMUNICATION),
    RECEIVED_EXTRACTED_RESOURCE_TRAIL(11, EventType.COMMUNICATION),
    SENT_PROCESSED_RESOURCE_TRAIL(12, EventType.COMMUNICATION),
    RECEIVED_PROCESSED_RESOURCE_TRAIL(13, EventType.COMMUNICATION),
    
    SENT_TRAIL(14, EventType.COMMUNICATION),
    RECEIVED_TRAIL(15, EventType.COMMUNICATION),
    
    SENT_BROADCAST_A(16, EventType.COMMUNICATION),
    RECEIVED_BROADCAST_A(17, EventType.COMMUNICATION),
    SENT_BROADCAST_B(18, EventType.COMMUNICATION),
    RECEIVED_BROADCAST_B(19, EventType.COMMUNICATION),
    SENT_BROADCAST_C(20, EventType.COMMUNICATION),
    RECEIVED_BROADCAST_C(21, EventType.COMMUNICATION),
    SENT_GENERIC_BROADCAST(22, EventType.COMMUNICATION),
    RECEIVED_GENERIC_BROADCAST(23, EventType.COMMUNICATION),
    
    SENT_UNICAST_A_CLOSEST(24, EventType.COMMUNICATION),
    RECEIVED_UNICAST_A_CLOSEST(25, EventType.COMMUNICATION),
    SENT_UNICAST_B_CLOSEST(26, EventType.COMMUNICATION),
    RECEIVED_UNICAST_B_CLOSEST(27, EventType.COMMUNICATION),
    SENT_UNICAST_C_CLOSEST(28, EventType.COMMUNICATION),
    RECEIVED_UNICAST_C_CLOSEST(29, EventType.COMMUNICATION),
    SENT_GENERIC_UNICAST_CLOSEST(30, EventType.COMMUNICATION),
    RECEIVED_GENERIC_UNICAST_CLOSEST(31, EventType.COMMUNICATION),
    
    SENT_UNICAST_A_CLIQUE(32, EventType.COMMUNICATION),
    RECEIVED_UNICAST_A_CLIQUE(33, EventType.COMMUNICATION),
    SENT_UNICAST_B_CLIQUE(34, EventType.COMMUNICATION),
    RECEIVED_UNICAST_B_CLIQUE(35, EventType.COMMUNICATION),
    SENT_UNICAST_C_CLIQUE(36, EventType.COMMUNICATION),
    RECEIVED_UNICAST_C_CLIQUE(37, EventType.COMMUNICATION),
    SENT_GENERIC_UNICAST_CLIQUE(38, EventType.COMMUNICATION),
    RECEIVED_GENERIC_UNICAST_CLIQUE(39, EventType.COMMUNICATION),
    
    MOVE_TO_CLOSEST_AGENT(40, EventType.MOTION),
    MOVE_TO_CLOSEST_COLLECTION_SITE(41, EventType.MOTION),
    MOVE_TO_PRIMARY_COLLECTION_SITE(42, EventType.MOTION),
    
    
    DROPPED_DETECTOR_REWARDS(44, EventType.REWARD),
    DROPPED_EXTRACTOR_REWARDS(45, EventType.REWARD),
    DROPPED_PROCESSOR_REWARDS(46, EventType.REWARD),
    
    RECEIVED_DETECTOR_REWARDS(47, EventType.REWARD),
    RECEIVED_EXTRACTOR_REWARDS(48, EventType.REWARD),
    RECEIVED_PROCESSOR_REWARDS(49, EventType.REWARD),
    
    
    
    ATTEMPT_DETECT(50, EventType.ATTEMPT_DETECT),
    ATTEMPT_EXTRACT(51,EventType.ATTEMPT_EXTRACT), 
    ATTEMPT_PROCESS(52,EventType.ATTEMPT_PROCESS), 
    ATTEMPT_TRANSPORT(53,EventType.ATTEMPT_TRANSPORT), 
    ATTEMPT_COMMUNICATE(54,EventType.ATTEMPT_COMMUNICATE);
    
    
    
    
    private int id;
    private EventType type;
    
    Event(int id, EventType type) {
    	this.id = id;
    	this.type = type;
    }
    
    public int getId() {
    	return this.id;
    }
    
    public EventType getType() {
	return this.type;
    }
    
}
