package com.synthverse.synthscape.core;

public enum EventType {
	MOTION,ATTEMPT_MOTION, REWARD, COMMUNICATION, DETECTION, EXTRACTION, PROCESSING, TRANSPORTATION, COLLECTION, ATTEMPT_DETECT, ATTEMPT_EXTRACT, ATTEMPT_PROCESS, ATTEMPT_TRANSPORT, ATTEMPT_COMMUNICATE;
}
